
// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:3000/video/

###


