// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@childAddress = 0xC13bF24Cc00564fA00C7161ea4DCCDd4E00e1d1C
// childAddressToken5: 0xC13bF24Cc00564fA00C7161ea4DCCDd4E00e1d1C

###
POST http://localhost:3000/api/child/userDatasJPG HTTP/1.1
content-type: application/json

{
  "from": "0x43e6B95803ac909f31C46517691cd2e33e298e40",
  "upload": "http://localhost:3000/img/Orientation_512x512.jpg",
  "name": "My token image",
  "symbol": "IMG",
  "description": "Token image paysage"
}

###
POST http://localhost:3000/api/child/userDatasMP4 HTTP/1.1
content-type: application/json

{
  "from": "0x43e6B95803ac909f31C46517691cd2e33e298e40",
  "upload": "http://localhost:3000/video/bigbuck.mp4",
  "name": "My token video",
  "symbol": "MP4",
  "description": "Token video animation"
}

###
