// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@childAddress = 0xC13bF24Cc00564fA00C7161ea4DCCDd4E00e1d1C
// childAddressToken5: 0xC13bF24Cc00564fA00C7161ea4DCCDd4E00e1d1C
@operator = 0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74
@owner = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@from = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@to = 0x91dDd8332bB2c94661D2192b15B93e27f0fEcEBA
// MintableERC721PredicateProxy
@predicate = 0x56E14C4C1748a818a5564D33cF774c59EB3eDF59

###
POST http://localhost:3000/api/child/details HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}"
}
###
POST http://localhost:3000/api/child/balance HTTP/1.1
content-type: application/json

{
  "owner": "{{owner}}",
  "nftAddress": "{{childAddress}}"
}

###
POST http://localhost:3000/api/child/tokenURI HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
###
POST http://localhost:3000/api/child/tokenByIndex HTTP/1.1
content-type: application/json

{
  "owner": "{{owner}}",
  "nftAddress": "{{childAddress}}",
  "index": 1
}
###
POST http://localhost:3000/api/child/total-supply HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}"
}
###
POST http://localhost:3000/api/child/is-approval-all HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "owner": "{{owner}}",
  "operator": "{{operator}}"
}
###
POST http://localhost:3000/api/child/approved HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
###
POST http://localhost:3000/api/child/encode-metadata HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
###
