// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@childAddress = 0xC13bF24Cc00564fA00C7161ea4DCCDd4E00e1d1C
// childAddressToken4: 
// childAddressToken5: 0xC13bF24Cc00564fA00C7161ea4DCCDd4E00e1d1C
@owner = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@from = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@to = 0x91dDd8332bB2c94661D2192b15B93e27f0fEcEBA
// POSContracts: 
@predicate = 0x56E14C4C1748a818a5564D33cF774c59EB3eDF59
// ERC721PredicateProxy: 0x74D83801586E9D3C4dc45FfCD30B54eA9C88cf9b
// MintableERC721PredicateProxy: 0x56E14C4C1748a818a5564D33cF774c59EB3eDF59

###
POST http://localhost:3000/api/child/mint HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "metadataCid": "QmZeYychcKrodnKo72JeSNdimeJ6AukrSNaPmsT2NpzdWE",
  "nftAddress": "{{childAddress}}"
}
###
POST http://localhost:3000/api/child/mint-factory HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "name": "My token video",
  "symbol": "MP4",
  "metadataCid": "QmZeYychcKrodnKo72JeSNdimeJ6AukrSNaPmsT2NpzdWE"
}
###
POST http://localhost:3000/api/child/exec-metadata HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "to": "{{to}}",
  "nftAddress": "{{childAddress}}",
  "tokenId": 3
}

###
POST http://localhost:3000/api/child/approve HTTP/1.1
content-type: application/json

{
  "owner": "{{owner}}",
  "nftAddress": "{{childAddress}}",
  "to": "{{to}}",
  "tokenId": 1
}
###
POST http://localhost:3000/api/child/approve-predicate HTTP/1.1
content-type: application/json

{
  "userAddress": "{{from}}",
  "nftAddress": "{{childAddress}}",
  "predicate": "{{predicate}}",
  "tokenId": 1
}
###
POST http://localhost:3000/api/child/approval-all HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "operator": "{{predicate}}",
  "approved": true
}
###
POST http://localhost:3000/api/child/transfer-from HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "to": "{{to}}",
  "nftAddress": "{{childAddress}}",
  "tokenId": 4
}
###
POST http://localhost:3000/api/child/safe-transfer-from-1 HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "to": "{{to}}",
  "nftAddress": "{{childAddress}}",
  "tokenId": 2
}
###
POST http://localhost:3000/api/child/approve HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "nftAddress": "{{childAddress}}",
  "tokenId": 3
}

###
POST http://localhost:3000/api/child/burn HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
