// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@pathURL = http://localhost:3000

###
POST {{pathURL}}/api/ipfs/pinFilePinata  HTTP/1.1
content-type: application/json
pinata_api_key: 7d7e3c042e0e43eac657
pinata_secret_api_key: cd8123ee3649aec0e3ba380b1588376bc20c3c520fecba6ed41819058d79ae8b
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Orientation_512x512.jpg"
Content-Type: image/jpg

< ./inputs/Orientation_512x512.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

{}
###
POST {{pathURL}}/api/ipfs/pinJsonPinata  HTTP/1.1
content-type: application/json
pinata_api_key: 7d7e3c042e0e43eac657
pinata_secret_api_key: cd8123ee3649aec0e3ba380b1588376bc20c3c520fecba6ed41819058d79ae8b

{
  "title":"title",
  "item_name": "item name",
  "author": "author",
  "description": "description",
  "type": "",
  "assertURI": "",
  "properties": {
    "width": "",
    "height": ""
  }
}
###
POST {{pathURL}}/api/ipfs/pinHashPinata  HTTP/1.1
content-type: application/json
pinata_api_key: 7d7e3c042e0e43eac657
pinata_secret_api_key: cd8123ee3649aec0e3ba380b1588376bc20c3c520fecba6ed41819058d79ae8b

{
  "hashToPin": "QmaQNPLWTSKNXCvzURSi3WrkywJ1qcnYC56Dw1XMrxYZ7Z"
}
###
POST {{pathURL}}/api/ipfs/ipfsText  HTTP/1.1
content-type: application/json

{}
