@pathURL = http://localhost:3002
@privatePINATA = <PINATA_KEY>
@secretPINATA = <PINATA_SECRET>

###
POST {{pathURL}}/api/ipfs/pinFilePinata  HTTP/1.1
content-type: application/json
pinata_api_key: {{privatePINATA}}
pinata_secret_api_key: {{secretPINATA}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Orientation_512x512.jpg"
Content-Type: image/jpg

< ./inputs/Orientation_512x512.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

{}
###
POST {{pathURL}}/api/ipfs/pinJsonPinata  HTTP/1.1
content-type: application/json
pinata_api_key: {{privatePINATA}}
pinata_secret_api_key: {{secretPINATA}}

{
  "title":"title",
  "item_name": "item name",
  "author": "author",
  "description": "description",
  "type": "",
  "assertURI": "",
  "properties": {
    "width": "",
    "height": ""
  }
}
###
POST {{pathURL}}/api/ipfs/pinHashPinata  HTTP/1.1
content-type: application/json
pinata_api_key: {{privatePINATA}}
pinata_secret_api_key: {{secretPINATA}}

{
  "hashToPin": "QmcYQStiHy2UJZg4AdDPuX1RuMh7zuaLmLkgRRXDMWk7eT"
}
###
POST {{pathURL}}/api/ipfs/ipfsText  HTTP/1.1
content-type: application/json

{
  "filesURL": [
    {
      "url1": "{{pathURL}}/text/file1.txt"
    },
    {
      "url2": "{{pathURL}}/svg-img/circle.svg"
    },
    {
      "url3": "{{pathURL}}/json/metadata.json"
    }
  ]
}
###
// Work In Progress
POST {{pathURL}}/api/ipfs/ipfsMedia  HTTP/1.1
content-type: application/json

{
  "filesURL": [
    {
      "url1": "{{pathURL}}/img/Orientation_512x512.jpg"
    },
    {
      "url2": "https://lasonotheque.org/UPLOAD/mp3/0564.mp3"
    },
    {
      "url3": "{{pathURL}}/video/yoga.mp4"
    }
  ]
}
###
POST {{pathURL}}/api/ipfs/ipfsRead  HTTP/1.1
content-type: application/json

{
  "directoryHash": "/ipfs/QmYT6vscRR76WMZds7WhStPPMnT7tHncunanjhBUKgfNYm",
  "file": "file1.txt"
}
###
POST {{pathURL}}/api/ipfs/ipfsDemo  HTTP/1.1
content-type: application/json

{
  "filesURL": [
    {
      "url1": "{{pathURL}}/text/file1.txt"
    },
    {
      "url2": "{{pathURL}}/svg-img/circle.svg"
    },
    {
      "url3": "{{pathURL}}/json/metadata.json"
    },
    {
      "url4": "{{pathURL}}/img/Orientation_512x512.jpg"
    },
    {
      "url5": "https://lasonotheque.org/UPLOAD/mp3/0564.mp3"
    },
    {
      "url6": "{{pathURL}}/video/yoga.mp4"
    }
  ]
}
