
// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://localhost:3000/api/posts/1  HTTP/1.1
content-type: application/json

{
  "title":"",
  "item_name": "",
  "author": "datas.author",
  "description": "datas.description",
  "type": "",
  "assertURI": "",
  "properties": {
    "width": "",
    "height": ""
  }
}
###


