
// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://localhost:3000/api/posts  HTTP/1.1
content-type: application/json

{
  "title":"title",
  "item_name": "nft",
  "author": "author",
  "description": "description",
  "type": "",
  "assertURI": "",
  "properties": {
    "width": "",
    "height": ""
  }
}
###

PUT http://localhost:3000/api/posts/1  HTTP/1.1
content-type: application/json

{
  "title":"title",
  "item_name": "nft",
  "author": "author",
  "description": "description",
  "type": "",
  "assertURI": "",
  "properties": {
    "width": "",
    "height": ""
  }
}
###

