@rootAddress = 0xcfef4df2832455630F521e6765F8362bF11Fe2BA
// rootAddressToken4: 0x8F24F733790f77849d8023aAd8737F8495C395A4
// rootAddressToken5: 0xcfef4df2832455630F521e6765F8362bF11Fe2BA
// rootAddressToken6: 0x1361d78d3375Eb11E0cc5a8a3423E3aC7c2513A5
@operator = 0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74
@owner = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@from = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@to = 0x91dDd8332bB2c94661D2192b15B93e27f0fEcEBA

###
POST http://localhost:3000/api/root/owner-of HTTP/1.1
content-type: application/json

{
   "from": "{{from}}",
   "rootToken": "{{rootAddress}}",
   "tokenId": 1
}
###
POST http://localhost:3000/api/root/events HTTP/1.1
content-type: application/json

{
   "from": "{{from}}",
   "rootToken": "{{rootAddress}}"
}
###
POST http://localhost:3000/api/root/balance HTTP/1.1
content-type: application/json

{
   "from": "{{from}}",
   "rootToken": "{{rootAddress}}"
}
###
POST http://localhost:3000/api/child/total-supply HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{rootAddress}}"
}
###
POST http://localhost:3000/api/child/is-approval-all HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{rootAddress}}",
  "owner": "{{owner}}",
  "operator": "{{operator}}"
}