@rootAddress = 0xcfef4df2832455630F521e6765F8362bF11Fe2BA
// rootAddressToken4: 0x8F24F733790f77849d8023aAd8737F8495C395A4
// rootAddressToken5: 0xcfef4df2832455630F521e6765F8362bF11Fe2BA
@owner = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@from = 0x43e6B95803ac909f31C46517691cd2e33e298e40
@to = 0x91dDd8332bB2c94661D2192b15B93e27f0fEcEBA
// POSContracts: 
@predicate = 0x56E14C4C1748a818a5564D33cF774c59EB3eDF59
// ERC721PredicateProxy: 0x74D83801586E9D3C4dc45FfCD30B54eA9C88cf9b
// MintableERC721PredicateProxy: 0x56E14C4C1748a818a5564D33cF774c59EB3eDF59

###
POST http://localhost:3000/api/root/grantRole HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "rootToken": "{{rootAddress}}",
  "predicate": "{{predicate}}",
  "role": "0x12ff340d0cd9c652c747ca35727e68c547d0f0bfa7758d2e77f75acef481b4f2"
}

###
POST http://localhost:3000/api/root/approve HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "rootToken": "{{rootAddress}}",
  "tokenId": 1
}
###
POST http://localhost:3000/api/root/approve-predicate HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "rootToken": "{{rootAddress}}",
  "predicate": "{{predicate}}",
  "tokenId": 1
}
###
POST http://localhost:3000/api/root/approval-all HTTP/1.1
content-type: application/json

{
  "from": "{{from}}",
  "operator": "{{predicate}}",
  "approved": true
}
###
POST http://localhost:3000/api/root/deposit HTTP/1.1
content-type: application/json

{
   "user": "{{from}}",
   "rootToken": "{{rootAddress}}",
   "tokenId": 1
}
###